@startuml
actor User
actor Administrator
actor System

usecase "Авторизация"
usecase "Регистрация"
usecase "Вход в систему"
usecase "Выход из системы"
usecase "Управление профилем"
usecase "Управление доступом"

User -->> "Авторизация"
User -->> "Регистрация"
User -->> "Вход в систему"
User -->> "Выход из системы"
User -->> "Управление профилем"

Administrator -->> "Управление доступом"
Administrator -->> "Управление профилем"

"Авторизация"..> "Вход в систему"
"Регистрация"..> "Вход в систему"
"Выход из системы"..> "Авторизация"
"Управление профилем"..> "Управление доступом"

System -->> "Авторизация"
System -->> "Вход в систему"
System -->> "Выход из системы"
System -->> "Управление профилем"
System -->> "Управление доступом"
@enduml